# Generated by Django 2.2.5 on 2019-10-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('main_photo', models.ImageField(upload_to='tricker_main/static/to_predict')),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
